### ISSUE TITLE
No module named 'keras.saving.hdf5_format'

### ISSUE THREAD

**Issue by SoaresAlisson** [AlexChristensen/transforEmotion#3]
Nice package, thank you!

I was trying to install it for the first time in my Linux, running the function `transformer_scores` but got these errors

```
Error in py_call_impl(callable, dots$args, dots$keywords) :
RuntimeError: Failed to import transformers.models.roberta.modeling_tf_roberta because of the following error (look up to see its traceback):
No module named 'keras.saving.hdf5_format'
```

And trying another module

```
Importing transformers module...
Error in py_call_impl(callable, dots$args, dots$keywords) :
RuntimeError: Failed to import transformers.models.roberta.modeling_tf_roberta because of the following error (look up to see its traceback):
No module named 'keras.saving.hdf5_format'
```

Thank you!

**Comment by AlexChristensen** [comment]
Thanks for pointing this out. There seems to be an issue with the versioning of the _keras_ module: https://stackoverflow.com/questions/74586892/no-module-named-keras-saving-hdf5-format

I'll take a crack at back versioning _keras_ after I try to reproduce the issue. I'll keep you posted (feel free to try back version _keras_ with {reticulate} if you want to give it a try)

**Comment by atomashevic** [comment]
Hi @SoaresAlisson,

It's been a while since you reported this issue. I wasn't able to reproduce this error after fresh install of the package on Linux.

Can you please check if the issue persits now after you run `reticulate::conda_update()`? It might have been an issue with tensorflow 2.11. Right now, `setup_miniconda` provides tensorwflow 2.13.1 and I'have experienced no issues (Ubuntu 23.04).

**Comment by atomashevic** [comment]
Closing due to the lack of feedback. The issue should be resolved with package now updating to tensorflow 2.13.1.
